apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./jetstack.yaml
  - ./bitnami.yaml
  - ./external-snapshotter.yaml
  - ./external-dns.yaml
  - ./prometheus-community.yaml
  - ./backube.yaml
  - ./local-path-provisioner.yaml
  - ./bjw-s.yaml
  - ./oauth2-proxy.yaml
  - ./emqx.yaml
  - ./cloudnative-pg.yaml
  - ./coder.yaml
  - ./argo.yaml
