apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cert-manager/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./external-snapshotter/ks.yaml
  - ./external-dns/ks.yaml
  - ./volsync/ks.yaml
  - ./keycloak/ks.yaml
  - ./oauth2-proxy/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./redis/ks.yaml
  - ./weave-gitops-dashboard/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./prometheus-json-exporter/ks.yaml
  - ./hosted/ks.yaml
  - ./minio/ks.yaml
  - ./argo-workflows/ks.yaml
  - ./portal/ks.yaml
  - ./coder/ks.yaml
  - ./paperless/ks.yaml
  - ./home-automation/ks.yaml
  - ./home-assistant/ks.yaml
  - ./n8n/ks.yaml
  - ./emqx-operator/ks.yaml
  - ./ring-mqtt/ks.yaml
  - ./zigbee2mqtt-sensors/ks.yaml
  - ./zigbee2mqtt-switches/ks.yaml
  # - ./nodered/ks.yaml
configMapGenerator:
- name: cluster-vars
  namespace: flux-system
  literals:
  - DOMAIN=raelix.com
  options:
    disableNameSuffixHash: true
