apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: message
resources:
  - ./namespace.yaml
  - ./mqtt-users.yaml
  - ./dashboard-auth.yaml
  - ./cluster.yaml
  - ./ingress.yaml
